# This is a basic workflow to help you get started with Actions

name: clone workflow

# Controls when the action will run. 
on: workflow_dispatch
jobs:
  # This workflow contains a single job called "build"
 job_one:
    name: clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              git clone git@github.com:jdrozar3/cmsc388t_winter21.git https://${{ secrets.HOST }}/~${{ secrets.USERNAME }}/ 

     
